import datetime

from drudge_data_classes import DrudgeLink

expected_drudge_links = [
  DrudgeLink(url='http://www.newsday.com/news/local/wire/newyork/ny-bc-ny--clinton-immigrati0405apr05,0,3809319,print.story?coll=ny-region-apnewyork', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='Sen. Clinton says immigration bill would make her a criminal...', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.washingtonpost.com/wp-dyn/content/article/2006/04/05/AR2006040501711_pf.html', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed="Clinton Deja Vu: Hillary Caught Stealing Bill's Old Lines...", is_top=False, is_splash=False),
  DrudgeLink(url='http://news.bbc.co.uk/1/hi/scotland/4881526.stm', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='Bird flu confirmed:  Dead swan in the UK', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.statesman.com/news/content/news/stories/local/04/5PIANKA.html', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='FBI INVESTIGATES PROFESSOR WHO ADVOCATES POPULATION WIPE-OUT..', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.breitbart.com/news/2006/04/05/D8GQ41804.html', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='Eminem Splits From Kim Mathers - Again...', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.breitbart.com/news/2006/04/05/060405140303.avirtttr.html', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='First H5N1 bird flu outbreak on German poultry farm...', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.breitbart.com/news/2006/04/05/D8GPU4FG0.html', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='Cats Seen at Risk in Bird Flu Zones...', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.breitbart.com/news/2006/04/05/060405110541.v6zvh8b8.html', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed="AOL Chief:  Internet will be tomorrow's TV screen...", is_top=False, is_splash=False),
  DrudgeLink(url='http://wnyt.com/x7668.xml?ag=x156&sb=x183', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed="Teacher charged for giving student 'wedgie'...", is_top=False, is_splash=False),
  DrudgeLink(url='http://www.breitbart.com/news/2006/04/05/D8GPRPI8F.html', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='Capitol Police Chief Denies Racism Charge in McKinney case...', is_top=False, is_splash=False),
  DrudgeLink(url='http://themediacrunch.com/2006/04/05/delay-mckinney/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='AUDIO...', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.kfvs12.com/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='Caught on Tape! High School Cameras Survives Tornado...', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.contactmusic.com/new/xmlfeed.nsf/mndwebpages/wal-mart%20hit%20by%20brokeback%20protest_04_04_06', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed="WAL-MART HIT BY 'BROKEBACK' PROTEST...", is_top=False, is_splash=False),
  DrudgeLink(url='http://www.lasvegassun.com/news/world/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='AP WORLD', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.lasvegassun.com/news/nation/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='AP NATIONAL', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.lasvegassun.com/news/beltway/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='AP WASHINGTON', is_top=False, is_splash=False),
  DrudgeLink(url='http://news.myway.com/index/id/business|ap.html', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='AP BUSINESS', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.newsday.com/entertainment/news/wire/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='AP ENTERTAINMENT', is_top=False, is_splash=False),
  DrudgeLink(url='http://news.myway.com/index/id/top|ap.html', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='AP ON THE HOUR', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.newsday.com/news/nationworld/wire/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='AP HEADLINES', is_top=False, is_splash=False),
  DrudgeLink(url='http://ap.tbo.com/breaking/national/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='AP BREAKING', is_top=False, is_splash=False),
  DrudgeLink(url='http://search.news.yahoo.com/search/news?p=a&c=news_photos', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='AP/REUTERS PHOTO WIRE', is_top=False, is_splash=False),
  DrudgeLink(url='http://hosted.ap.org/dynamic/files/specials/videolineups/audio.html?SITE=MNROC&SECTION=HOME', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='AP AUDIO', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.ananova.com/news/index.html?nav_src=news&menu=news.latestheadlines', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='ANANOVA', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.bloomberg.com/news/top.html', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='BLOOMBERG', is_top=False, is_splash=False),
  DrudgeLink(url='http://news.nasdaq.com/aspxcontent/newsheadlines.aspx?&selected=9999', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='DOW JONES', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.efenews.com/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='EFE', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.ians.in', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='INDO-ASIAN NEWS SERVICE', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.interfax.com', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='INTERFAX', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.irna.ir', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='ISLAMIC REPUBLIC WIRE', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.itar-tass.com/eng/level2.html?GroupID=146', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='ITAR-TASS', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.realcities.com/mld/krwashington/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='KNIGHT RIDDER [DC]', is_top=False, is_splash=False),
  DrudgeLink(url='http://home.kyodo.co.jp/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='KYODO', is_top=False, is_splash=False),
  DrudgeLink(url='http://english.pravda.ru/allnews_en.html', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='PRAVDA', is_top=False, is_splash=False),
  DrudgeLink(url='http://uk.news.yahoo.com/75/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='PRESS ASSOCIATION', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.prnewswire.com/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='PR NEWSWIRE', is_top=False, is_splash=False),
  DrudgeLink(url='http://biz.yahoo.com/n/y/y0010.html', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='[SHOWBIZ] PR WIRE', is_top=False, is_splash=False),
  DrudgeLink(url='http://public.shns.com', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='SCRIPPS HOWARD', is_top=False, is_splash=False),
  DrudgeLink(url='http://usinfo.state.gov/usinfo/products/washfile.html', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='US INFO  WIRE', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.usnewswire.com/topnews/current.htm', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='U.S. NEWSWIRE', is_top=False, is_splash=False),
  DrudgeLink(url='http://uk.news.yahoo.com/588/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='WENN SHOWBIZ', is_top=False, is_splash=False),
  DrudgeLink(url='http://7am.com/wireidx/world/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='WORLDWIRES', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.xinhuanet.com/english/index.htm', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='XINHUA', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.newseum.org/todaysfrontpages/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='WORLD FRONT PAGES', is_top=False, is_splash=False),
  DrudgeLink(url='http://tv.zap2it.com/tveditorial/tve_main/1,1002,272|||daily,00.html', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='TV RATINGS', is_top=False, is_splash=False),
  DrudgeLink(url='http://boxofficemojo.com/daily/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='MOVIE BOXOFFICE RESULTS', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.abcnews.com/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='ABCNEWS', is_top=False, is_splash=False),
  DrudgeLink(url='http://abcnews.go.com/sections/politics/TheNote/TheNote.html', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='ABCNEWS THE NOTE', is_top=False, is_splash=False),
  DrudgeLink(url='http://adage.com/news_and_features/deadline/index.html', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='AD AGE DEADLINE', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.amconmag.com', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='AMERICAN CONSERVATIVE', is_top=False, is_splash=False),
  DrudgeLink(url='http://news.bbc.co.uk/default.stm', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='BBC', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.bbc.co.uk/worldservice/news/summary.ram', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='BBC AUDIO', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.billboard.com', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='BILLBOARD', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.boston.com/globe/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='BOSTON GLOBE', is_top=False, is_splash=False),
  DrudgeLink(url='http://news.bostonherald.com/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='BOSTON HERALD', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.tvinsite.com/broadcastingcable/index.asp?layout=webzine', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='BROADCASTING & CABLE', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.cbsnews.com', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='CBS NEWS', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.cbsnews.com/sections/publiceye/main500486.shtml', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='CBS PUBLIC EYE...', is_top=False, is_splash=False),
  DrudgeLink(url='http://inside.c-spanarchives.org:8080/cspan/cspan.csp?command=dschedule', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='C-SPAN SCHEDULE', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.chicagotribune.com', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='CHICAGO TRIB', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.suntimes.com/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='CHICAGO SUN-TIMES', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.csmonitor.com/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='CHRISTIAN SCIENCE', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.cnn.com', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='CNN', is_top=False, is_splash=False),
  DrudgeLink(url='http://cnn.com/TRANSCRIPTS/index.html', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='CNN TRANSCRIPTS', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.variety.com/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='DAILY VARIETY', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.washtimes.com/national/daybook.htm', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='D.C. DAYBOOK', is_top=False, is_splash=False),
  DrudgeLink(url='http://dailynews.yahoo.com/h/en/eo/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='E!', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.economist.com', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='ECONOMIST', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.editorandpublisher.com/eandp/index.jsp', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='EDITOR & PUBLISHER', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.tvweek.com', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='ELECTRONIC MEDIA', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.emiratestodayonline.com/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='EMIRATES TODAY...', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.emergency.com/ennday.htm', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='EMERGENCY NET', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.empireonline.co.uk/site/news/index.asp', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='EMPIRE [MOVIES]', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.pathfinder.com/ew/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='ENT WEEKLY', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.ft.com', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='FINANCIAL TIMES', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.forbes.com/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='FORBES MAG', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.foxnews.com', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='FOX NEWS', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.hellomagazine.com/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='HELLO!', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.hillnews.com', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='HILL', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.hollywoodreporter.com', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed="H'WOOD REPORTER", is_top=False, is_splash=False),
  DrudgeLink(url='http://www.huffingtonpost.com', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='HUFFINGTON POST', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.humaneventsonline.com', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='HUMAN EVENTS', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.insightmag.com/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='INSIGHT MAG', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.iht.com', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='INTERNATIONAL HERALD TRIB', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.investors.com', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='INVEST BUS DAILY', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.jpost.com/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='JERUSALEM POST', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.jewishworldreview.com', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='JEWISH WORLD REVIEW', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.dailynewslosangeles.com/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='LA DAILY NEWS', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.latimes.com', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='LA TIMES', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.lexisnexis.com/news', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='LEXISNEXIS NEWS', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.lucianne.com', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='LUCIANNE.COM', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.mediaresearch.org/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='MEDIA CHECK', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.medialifemagazine.com/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='MEDIA LIFE', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.mediaweek.com', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='MEDIA WEEK', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.msnbc.msn.com', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='MSNBC', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.muchmusic.com/news/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='MUCHMUSIC', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.TheNation.com', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='NATION', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.nationalenquirer.com/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='NATIONAL ENQUIRER', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.nationalreview.com', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='NATIONAL REVIEW', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.thenewrepublic.com/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='NEW REPUBLIC', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.nydailynews.com/news/todays_headlines/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='NY DAILY NEWS', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.observer.com/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='NY OBSERVER', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.nypost.com/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='NY POST', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.nytimes.com/info/contents/textpath.html', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='NY TIMES', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.newyorker.com', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='NEW YORKER', is_top=False, is_splash=False),
  DrudgeLink(url='http://newsbusters.org/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='NEWSBUSTERS', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.newsbytes.com', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='NEWSBYTES', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.newsmax.com', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='NEWSMAX', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.newsweek.com/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='NEWSWEEK', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.kcna.co.jp/index-e.htm', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='N. KOREAN NEWS', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.people.com', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='PEOPLE MAG', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.radioandrecords.com', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='R & R', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.reasonmag.com/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='REASON MAG', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.rollcall.com/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='ROLL CALL', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.sky.com/skynews/home', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='SKY NEWS', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.slate.com/Code/TodaysPapers/TodaysPapers.asp', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='SLATE: PAPERS', is_top=False, is_splash=False),
  DrudgeLink(url='http://thesmokinggun.com/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='SMOKING GUN', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.starmagazine.com', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='STAR', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.smh.com.au/text/index.html', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='SYDNEY MORNING HERALD', is_top=False, is_splash=False),
  DrudgeLink(url='http://time.com', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='TIME MAG', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.TMZ.com', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='TMZ', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.tvspy.com/shoptalk.cfm', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='TV SHOPTALK', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.dailymail.co.uk/pages/live/dailymail/home.html', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='[U.K.] DAILY MAIL', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.mirror.co.uk', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='[U.K.] DAILY MIRROR', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.dailyrecord.co.uk/news/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='DAILY RECORD', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.thisislondon.com/news/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='[U.K.] EVENING STANDARD', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.express.co.uk', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='[U.K.] EXPRESS', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.guardian.co.uk/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='[U.K.] GUARDIAN', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.independent.co.uk/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='[U.K.] INDEPENDENT', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.newsoftheworld.co.uk/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='[U.K.] NEWS OF THE WORLD', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.megastar.co.uk/site/today/news/latest/index.html', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='[U.K.] STAR', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.thesun.co.uk', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='[U.K.] SUN', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.telegraph.co.uk/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='[U.K.] TELEGRAPH', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.thetimes.co.uk', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='[U.K.] TIMES', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.usnews.com/usnews/home.htm', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='US NEWS', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.usatoday.com/usatonline/newsindex11.htm', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='USA TODAY', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.villagevoice.com/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='VILLAGE VOICE', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.washingtonpost.com/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='WASH POST', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.washtimes.com', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='WASH TIMES', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.theweekmagazine.com/index.asp', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='THE WEEK', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.weeklystandard.com', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='WEEKLY STANDARD', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.WorldNetDaily.com/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='WORLDNETDAILY', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.breitbart.com/news/2006/04/05/D8GQ1F0GC.html', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='POLICE UNCOVER SHOCK EMAIL IN DUKE LACROSSE RAPE CASE...', is_top=False, is_splash=False),
  DrudgeLink(url='http://news.yahoo.com/s/ap/20060405/ap_on_sp_ot/duke_lacrosse_investigation_5', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='Coach quits, season canceled...', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.thesmokinggun.com/archive/0405061duke1.html', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='Search Warrant...', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.latimes.com/news/nationworld/nation/la-na-jeb5apr05,0,4076175.story?coll=la-home-headlines', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed="Florida Gov. Bush Calls Tone of Immigration Debate 'Hurtful'...", is_top=False, is_splash=False),
  DrudgeLink(url='http://www.breitbart.com/news/2006/04/05/D8GPRBR02.html', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='Push for  Vote...', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.drudgereportarchives.com/data/2006/04/06/20060406_000558_flash1hr.htm', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed="FLASHBACK: Dem Senate Leader Harry Reid: 'Our Federal Wallet Stretched To Limit By Illegal Aliens Getting Welfare'...", is_top=False, is_splash=False),
  DrudgeLink(url='http://www.woai.com/news/local/story.aspx?content_id=657E011F-7620-4724-81D5-6EB8128E7DCF', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='Principal Joins High School Walkout...', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.contactmusic.com/new/xmlfeed.nsf/mndwebpages/stone%20to%20direct%20basic%20instinct%203_05_04_2006', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed="I'LL DO IT MYSELF:  SHARON STONE TO DIRECT 'BASIC INSTINCT 3'...", is_top=False, is_splash=False),
  DrudgeLink(url='http://www.breitbart.com/news/2006/04/05/060405141746.b7qf2qbf.html', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed="Canadian teen faces US 'war on terror' tribunal...", is_top=False, is_splash=False),
  DrudgeLink(url='http://www.boston.com/news/nation/washington/articles/2006/04/05/kennedy_book_blasts_bush_preventive_war/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed="Sen. Kennedy blasts Bush, 'preventive war' in new book...", is_top=False, is_splash=False),
  DrudgeLink(url='http://www.drudgereportarchives.com/data/2006/04/06/20060406_000558_flash9ab.htm', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='MATT DRUDGE', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.mirror.co.uk/3am/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='3 AM GIRLS', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.nypost.com/gossip/cindy/cindy.htm', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='CINDY ADAMS', is_top=False, is_splash=False),
  DrudgeLink(url='http://alter.newsweek.msnbc.com', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='JONATHAN ALTER', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.armyarcherd.com', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='ARMY ARCHERD', is_top=False, is_splash=False),
  DrudgeLink(url='http://blogs.herald.com/dave_barrys_blog/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='DAVE BARRY', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.variety.com/index.asp?layout=columns_top5&categoryid=1&cs=1', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='PETER BART', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.tvguide.com/news/thebiz/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='STEPHEN BATTAGLIO', is_top=False, is_splash=False),
  DrudgeLink(url='http://u.dailynews.com/Stories/0,1413,211%257E23520%257E,00.html', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='BECK/SMITH', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.thesun.co.uk/section/0,,4,00.html', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='BIZARRE [SUN]', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.washingtontimes.com/op-ed/tblankley.htm', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='TONY BLANKLEY', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.opendemocracy.net/democracy/illusion_3367.jsp', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='SIDNEY BLUMENTHAL', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.usnews.com/usnews/opinion/ophome.htm', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='GLORIA BORGER', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.mediaresearch.org/BozellColumns/bozellnewswelcome.asp', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='BRENT BOZELL', is_top=False, is_splash=False),
  DrudgeLink(url='http://washingtonpost.com/wp-dyn/politics/columns/broderdavid/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='DAVID BRODER', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.nytimes.com/top/opinion/editorialsandoped/oped/columnists/davidbrooks/index.html', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='DAVID BROOKS', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.wnd.com/news/archives.asp?AUTHOR_ID=185', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='PAT BUCHANAN', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.nationalreview.com/buckley/buckley.asp', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='BILL BUCKLEY', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.townhall.com/columnists/monacharen/archive.shtml', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='MONA CHAREN', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.msnbc.msn.com/id/12098907/site/newsweek/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='ELEANOR CLIFT', is_top=False, is_splash=False),
  DrudgeLink(url='http://sitesearch.washingtonpost.com/cgi-bin/search99.pl?searchdatabase=serf&serf_wp=on&wp=on&day_count=14&byline=Richard+Cohen&source=post/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='RICHARD COHEN', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.observer.com/pages/conason.htm', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='JOE CONASON', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.davidcorn.com', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='DAVID CORN', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.anncoulter.com', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='ANN COULTER', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.cq.com/public/crawford_current.html', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='CRAIG CRAWFORD', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.nydailynews.com/news/col/story/405261p-343192c.html', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='STANLEY CROUCH', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.nydailynews.com/news/story/406078p-343860c.html', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='MICHAEL DALY', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.cnn.com/CNN/Programs/lou.dobbs.tonight/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='LOU DOBBS', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.washtimes.com/commentary/20060402-112825-9830r.htm', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='DE BORCHGRAVE', is_top=False, is_splash=False),
  DrudgeLink(url='http://rogerebert.suntimes.com/apps/pbcs.dll/frontpage', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='ROGER EBERT', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.worldnetdaily.com/news/archives.asp?AUTHOR_ID=20', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='LARRY ELDER', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.creators.com/opinion_show.cfm?columnsName=ses', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='SUSAN ESTRICH', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.wnd.com/news/archives.asp?AUTHOR_ID=134', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='JOSEPH FARAH', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.townhall.com/columnists/suzannefields/archive.shtml', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='SUZANNE FIELDS', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.msnbc.msn.com/id/11786788/site/newsweek', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='HOWARD FINEMAN', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.deadlinehollywooddaily.com', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='NIKKI FINKE', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.variety.com/index.asp?layout=bio&peopleID=1231', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='MICHAEL FLEMING', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.foxnews.com/column_archive/0,2976,6,00.html', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='ROGER FRIEDMAN', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.opinionjournal.com/diary/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='JOHN FUND', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.sfgate.com/cgi-bin/srch_archive/columnists.cgi?waisdbname=/web/sfgate/wais/chronicle/&byline=leah+garchik', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='LEAH GARCHIK', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.gertzfile.com', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='BILL GERTZ', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.uexpress.com/georgieannegeyer/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='GEORGIE GEYER', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.techcentralstation.com/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='JIM GLASSMAN', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.nationalreview.com/goldberg/goldberg.asp', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='JONAH GOLDBERG', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.boston.com/news/globe/editorial_opinion/oped/goodman/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='ELLEN GOODMAN', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.cnn.com/2005/LAW/06/09/grace.jackson.trial/index.html', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='NANCY GRACE', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.nydailynews.com/news/col/grove/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='LLOYD GROVE', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.hollywoodreporter.com/thr/columns/grove.jsp', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='MARTIN GROVE', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.miami.com/mld/miamiherald/news/columnists/carl_hiaasen/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='CARL HIAASEN', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.villagevoice.com/hentoff', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='NAT HENTOFF', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.hitchensweb.com', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='CHRISTOPHER HITCHENS', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.washtimes.com/national/inbeltway.htm', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='INSIDE BELTWAY', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.washtimes.com/national/inpolitics.htm', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='INSIDE POLITICS', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.gertzfile.com/gertzfile/InsidetheRing.html', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='INSIDE THE RING', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.creators.com/opinion_show.cfm?columnsName=miv', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='MOLLY IVINS', is_top=False, is_splash=False),
  DrudgeLink(url='http://washingtonpost.com/wp-dyn/politics/fedpage/columns/intheloop/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='AL KAMEN', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.kausfiles.com/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='MICKEY KAUS', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.washingtonpost.com/wp-dyn/opinion/columns/kinsleymichael', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='MICHAEL KINSLEY', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.time.com/time/columnist/klein', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='JOE KLEIN', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.aintitcool.com/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='HARRY KNOWLES', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.washingtonpost.com/wp-dyn/opinion/columns/krauthammercharles/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='KRAUTHAMMER', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.nytimes.com/top/opinion/editorialsandoped/oped/columnists/paulkrugman/index.html', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='PAUL KRUGMAN', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.nationalreview.com/kudlow/kudlow.asp', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='LARRY KUDLOW', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.washingtonpost.com/wp-dyn/style/columns/medianotes/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='HOWIE KURTZ', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.townhall.com/columnists/johnleo/archive.shtml', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='JOHN LEO', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.worldnetdaily.com/news/archives.asp?AUTHOR_ID=10', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='DAVID LIMBAUGH', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.rushlimbaugh.com', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='RUSH LIMBAUGH', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.wnd.com/news/archives.asp?AUTHOR_ID=12', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='HAL LINDSEY', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.nationalreview.com/lowry/lowry.shtml', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='RICH LOWRY', is_top=False, is_splash=False),
  DrudgeLink(url='http://michellemalkin.com/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='MICHELLE MALKIN', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.whitehouse.gov/news/briefings/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='SCOTT MCCLELLAN', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.vote.com/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='DICK MORRIS', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.opinionjournal.com/columnists/pnoonan/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='PEGGY NOONAN', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.suntimes.com/index/novak.html', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='BOB NOVAK', is_top=False, is_splash=False),
  DrudgeLink(url='http://rosie.com', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed="ROSIE O'DONNELL", is_top=False, is_splash=False),
  DrudgeLink(url='http://www.observer.com/media_offtherecord.asp', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='OFF THE RECORD', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.townhall.com/columnists/marvinolasky/archive.shtml', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='MARVIN OLASKY', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.boston.com/news/globe/editorial_opinion/oped/oliphant/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='THOMAS OLIPHANT', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.jewishworldreview.com/cols/oreilly_archives.asp', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed="BILL O'REILLY", is_top=False, is_splash=False),
  DrudgeLink(url='http://www.nypost.com/gossip/pagesix/pagesix.htm', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='PAGE SIX', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.newsday.com/news/columnists/ny-jamespinkerton,0,5081177.columnist', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='JIM PINKERTON', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.billpress.com', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='BILL PRESS', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.mediabistro.com/tvnewser/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='TV NEWSER', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.mediaweek.com/mediaweek/buzz/columnists/berman.jsp', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='TV PROGRAMMING INSIDER', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.washtimes.com/national/pruden.htm', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='WES PRUDEN', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.msnbc.msn.com/id/11785818/site/newsweek/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='ANNA QUINDLEN', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.observer.com/culture_rexreed.asp', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='REX REED', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.richardreeves.com/latest_column.html', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='RICHARD REEVES', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.washingtonpost.com/wp-dyn/style/columns/reliablesource/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='RELIABLE SOURCE', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.suntimes.com/index/roeper.html', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='RICHARD ROEPER', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.nydailynews.com/news/gossip', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='RUSH/MOLLOY', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.eagleforum.org/column', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='SCHLAFLY', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.washingtonpost.com/wp-dyn/style/columns/shalestom/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='TOM SHALES', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.philly.com/mld/philly/entertainment/columnists/gail_shister/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='GAIL SHISTER', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.nypost.com/gossip/liz.htm', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='LIZ SMITH', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.suntimes.com/index/sneed.html', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='MICHAEL SNEED', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.sobran.com/columns', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='JOE SOBRAN', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.townhall.com/columnists/thomassowell/archive.shtml', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='THOMAS SOWELL', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.andrewsullivan.com', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='ANDREW SULLIVAN', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.thebostonchannel.com/helenthomas/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='HELEN THOMAS', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.jewishworldreview.com/cols/thomas1.asp', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='CAL THOMAS', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.washingtonpost.com/wp-dyn/style/columns/tvcolumn/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='TV COLUMN', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.reviewjournal.com/columnists/clarke.html', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='VEGAS CONFIDENTIAL', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.hollywood-elsewhere.com/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='JEFFREY WELLS', is_top=False, is_splash=False),
  DrudgeLink(url='http://jewishworldreview.com/cols/will1.asp', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='GEORGE WILL', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.townhall.com/columnists/walterwilliams/archive.shtml', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='WALTER WILLIAMS', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.usnews.com/usnews/politics/whispers/whisphome.htm', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='WASHINGTON WHISPERS', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.jameswolcott.com/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='JAMES WOLCOTT', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.usnews.com/usnews/opinion/mzuckerman.htm', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='MORT ZUCKERMAN', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.suntimes.com/index/zwecker.html', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='BILL ZWECKER', is_top=False, is_splash=False),
  DrudgeLink(url='http://themediacrunch.com/2006/04/05/cbsdrudge/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed="CBS NEWSROOM TUNES TO 'DRUDGE REPORT' DURING COURIC PEP RALLY...", is_top=False, is_splash=False),
  DrudgeLink(url='http://www.wnbc.com/news/8479376/detail.html', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed="I'M GOING!", is_top=False, is_splash=False),
  DrudgeLink(url='http://www.drudgereportarchives.com/data/2006/04/06/20060406_000558_flash1cl.htm', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='CBS PRESS RELEASE...', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.drudgereportarchives.com/data/2006/04/06/20060406_000558_flash.htm', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed="SCHIEFFER: 'I think we're going to love you'...", is_top=False, is_splash=False),
  DrudgeLink(url='http://www.drudgereportarchives.com/data/2006/04/06/20060406_000558_flash1z.htm', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='ZUCKER/WRIGHT E-MAIL ABOUT COURIC...', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.bloomberg.com/apps/news?pid=washingtonstory&sid=afgZZj1sxB5w', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed="William F. Buckley Jr.:   Hillary 'might easily be president'...", is_top=False, is_splash=False),
  DrudgeLink(url='http://news.tbo.com/news/metro/MGBB3U7ZMLE.html', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='Homeland Security official arrested in sex sting...', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.breitbart.com/news/2006/04/05/D8GPR8882.html', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed="'Using a computer to seduce child'...", is_top=False, is_splash=False),
  DrudgeLink(url='http://www.dailymail.co.uk/pages/live/articles/news/news.html?in_article_id=382039&in_page_id=1770&in_a_source=', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='Man held as terrorism suspect over punk song...', is_top=False, is_splash=False),
  DrudgeLink(url="javascript:window.location.href='http://www.drudgereport.com/default.htm?sc='+Math.random();", page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='REFRESH DRUDGE REPORT FOR LATEST...', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.drudgereportarchives.com/dsp/links_recap.htm', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='RECENT DRUDGE HEADLINES', is_top=False, is_splash=False),
  DrudgeLink(url='http://sg.news.yahoo.com/world/afp.html', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='AGENCE FRANCE-PRESSE', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.voila.co.uk/News/afp/int/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='AFP INTERNATIONAL', is_top=False, is_splash=False),
  DrudgeLink(url='http://search.asia.yahoo.com/search/news_asia?p=AFP+World+News+Summary', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='AFP NEWS WRAP', is_top=False, is_splash=False),
  DrudgeLink(url='http://cnn.netscape.cnn.com/news/search.jsp?q=%22WORLD+NEWS+HIGHLIGHTS%22&w=ALL&f=336&x=0&y=0', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='REUTERS WORLD NEWS HIGHLIGHTS', is_top=False, is_splash=False),
  DrudgeLink(url='http://channels.netscape.com/ns/news/search.jsp?fs=t&q=World+News+Digest', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='REUTERS DIGEST', is_top=False, is_splash=False),
  DrudgeLink(url='http://today.reuters.com/news/newsChannel.aspx?type=worldNews', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='REUTERS WORLD', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.breitbart.com/?feed=reuters&cat=pol', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='REUTERS POLITICS', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.breitbart.com/?feed=reuters&cat=odd', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='REUTERS ODD', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.upi.com/NewsTrack/', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='UPI ALL', is_top=False, is_splash=False),
  DrudgeLink(url='http://interestalert.com/remote/siteia/morenews.shtml?Sys=siteia&Fid=WORLDNEW&Type=News&Title=World%20News', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='UPI WORLD', is_top=False, is_splash=False),
  DrudgeLink(url='http://news.google.com/nwshp?hl=en&tab=wn&q=', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='GOOGLE NEWS', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.drudgereport.com/wx.htm', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='WEATHER ACTION', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.drudgereport.com/quake.htm', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='QUAKE SHEET', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.militarycity.com/valor/honor.html', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='THE LIST...', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.drudgereportArchives.com', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='DRUDGE ARCHIVES', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.refdesk.com', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='DRUDGE REFERENCE DESK', is_top=False, is_splash=False),
  DrudgeLink(url='mailto:drudge@drudgereport.com', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='EMAIL: DRUDGE@DRUDGEREPORT.COM', is_top=False, is_splash=False),
  DrudgeLink(url='http://www.intermarkets.net/drudgereport.htm', page_dt=datetime.datetime(1970, 1, 1, 0, 0), hed='BE SEEN!   RUN ADS ON DRUDGE REPORT...', is_top=False, is_splash=False)
]
